delete from sys_para;

-- 产品配置
delete from sys_para where para_id in('1','2','3');
INSERT INTO sys_para VALUES ('1', 'sys_Name', '海云数服', 'server.properties', '系统名称最多输入8个字');
INSERT INTO sys_para VALUES ('2', 'logo_img', 'hyrenlogo.png', 'server.properties', '系统logo图片名称');
INSERT INTO sys_para VALUES ('3', 'logo_depict', '博彦科技(上海)有限公司', 'server.properties', 'logo描述信息');
INSERT INTO sys_para VALUES ('12', 'platform', 'normal', 'server.properties', 'normal:不做集群认证;cdh5_13:CDH平台认证;fic50、fic60、fic70、fic80:FI平台认证,不配置默认normal');
INSERT INTO sys_para VALUES ('102', 'summary_volumn', '3', 'server.properties', '摘要获取行数');
INSERT INTO sys_para VALUES ('103', 'collection', 'HrdsFullTextIndexing', 'server.properties', 'solr的collection');
INSERT INTO sys_para VALUES ('104', 'agentpath', '/home/hyshf/HRDS/HrdsServer/tmp/hrds_Agent.tar.gz', 'server.properties', '下载agent的文件');
INSERT INTO sys_para VALUES ('108', 'isagenttohadoop', '2', 'server.properties', 'agent和集群是否在一台机器上2：在；1：不在');
INSERT INTO sys_para VALUES ('109', 'hyren_host', '172.168.0.203', 'server.properties', 'HYREN服务器IP');
INSERT INTO sys_para VALUES ('110', 'hyren_port', '2000', 'server.properties', 'HYREN服务器接受进程端口');
INSERT INTO sys_para VALUES ('111', 'hyren_osname', 'linux', 'server.properties', 'HYREN服务器操作系统');
INSERT INTO sys_para VALUES ('112', 'hyren_storedir', '/home/hyshf/HRDS/HrdsServer/bigserver/data/', 'server.properties', 'HYREN服务器数据传输落地目录');
INSERT INTO sys_para VALUES ('113', 'customHandler', '/reloadDictionary', 'server.properties', '访问自定义solr handler请求,加载solr词典');
INSERT INTO sys_para VALUES ('114', 'solrUrl', 'http://172.168.0.201:8983/solr/', 'server.properties', 'solr访问地址');
INSERT INTO sys_para VALUES ('115', 'thresholdFileSize', '26214400', 'server.properties', '文件采集大文件阈值，默认25MB');
INSERT INTO sys_para VALUES ('116', 'singleAvroSize', '536870912', 'server.properties', '文件采集单个Avro的大小，默认512MB');
INSERT INTO sys_para VALUES ('118', 'hivehouse', '/hrds/hive/warehouse', 'server.properties', 'hive仓库目录');
INSERT INTO sys_para VALUES ('128', 'zkHost', '172.168.0.3:24002,172.168.0.2:24002,172.168.0.1:24002/solr', 'server.properties', 'solr的zookeeper配置');
INSERT INTO sys_para VALUES ('129', 'solrclassname', 'opersolr.OperSolrImpl5_3_1', 'server.properties', 'solr具体实现类全名opersolr.OperSolrImpl4_9_1(cdh)或opersolr.OperSolrImpl5_3_1');
INSERT INTO sys_para VALUES ('130', 'hive_local_file', '/home/hyshf/HRDS/HrdsServer/hive', 'server.properties', '数据集市本地存储目录（csv）');
INSERT INTO sys_para VALUES ('131', 'hbase_data_path', '/hbase/data/default', 'server.properties', '(监控)hbase存储目录');
INSERT INTO sys_para VALUES ('132', 'file_collect_path', '/hrds/*/*/*/*/avro_*', 'server.properties', '(监控)文件采集存储目录');
INSERT INTO sys_para VALUES ('133', 'hdfsfile_Replication_num', '7', 'server.properties', 'hdfs中,文件默认存放时间(天)');
INSERT INTO sys_para VALUES ('134', 'language', 'eng', 'server.properties', 'ocr识别语言，eng（英文）或者chi_sim，默认chi_sim（简体中文）');
INSERT INTO sys_para VALUES ('135', 'HADOOP_USER_NAME', 'hyshf', 'server.properties', '程序运行所需用户名');
INSERT INTO sys_para VALUES ('136', 'pathprefix', '/hrds', 'server.properties', 'hdfs上的目录规范，此目录必须为hdfs的根目录，即必须以 \"/\"开头');
INSERT INTO sys_para VALUES ('137', 'monitoring_frequency', '30000', 'server.properties', '监控频率（单位毫秒）');
INSERT INTO sys_para VALUES ('138', 'cluster', 'gpfdist://172.168.0.94:8889', 'server.properties', 'GP或者ELK的外部表映射文件服务地址(GP写法：gpfdist://172.168.0.94:5000；elk写法：gsfs://172.168.0.26:5000)');
INSERT INTO sys_para VALUES ('139', 'system_language', 'zh_CN', 'server.properties', '服务器系统语言(默认zh_CN,例如英文；en_US)');
INSERT INTO sys_para VALUES ('140', 'gpfdistRootDir', '/home/hyshf/HRDS', 'server.properties', 'gpfdist服务起的目录');
INSERT INTO sys_para VALUES ('142', 'use_phoenix', '1', 'server.properties', '是：0 （映射phoenix），否：1 （不使用）');
INSERT INTO sys_para VALUES ('143', 'principle.name', 'admin@HADOOP.COM', 'server.properties', 'FI认证用户的principlename');
INSERT INTO sys_para VALUES ('144', 'ml_rpc_address', 'http://172.168.0.91:9090', 'server.properties', '机器学习rpc服务地址');
INSERT INTO sys_para VALUES ('146', 'kafkaAgent', '/home/hyshf/HRDS/HrdsServer/kafka/kafka_Agent.tar.gz', 'server.properties', '下载agent的文件');
INSERT INTO sys_para VALUES ('147', 'solrOnHbase', 'HrdsHbaseOverSolr', 'server.properties', 'solrOnHbase的collection');
INSERT INTO sys_para VALUES ('148', 'kafka_zk_list', '172.168.0.91:2181,172.168.0.92:2181,172.168.0.93:2181', 'server.properties', 'kafka集群的zk');
INSERT INTO sys_para VALUES ('149', 'ispostgres', '1', 'server.properties', '没有elk或者gp时用postgresql做增量(默认1否),此时修改原gp或elk的连接为postgresql的连接,相关表空间查看create文件');
INSERT INTO sys_para VALUES ('150', 'overlord_address', '10.154.6.200:8090', 'server.properties', 'druid提交索引服务的地址');

INSERT INTO sys_para VALUES ('151', 'isSysDump', '0', 'server.properties', '是否打开数据库自动备份，是：0；否：1');
INSERT INTO sys_para VALUES ('152', 'sysDumpTime', 'D-20170101102039', 'server.properties', '数据库自动备份时间，配置如：Y-14位日期(每年指定日期);M-14位日期(每月指定日期);D-14位日期(每天指定日期);H-14位日期(每小时指定日期)');

INSERT INTO sys_para VALUES ('153', 'dqcTS', 'dqc', 'server.properties', '数据质量数据的表空间');
INSERT INTO sys_para VALUES ('154', 'jgusecb', '0', 'server.properties', '数据加工使用工具(1->gp,0->carbondata)');
INSERT INTO sys_para VALUES ('156', 'restFilePath', '/home/hyshf/HRDS', 'server.properties', '接口数据文件的存放路径');
INSERT INTO sys_para VALUES ('157', 'ksql_schema_address', 'http://172.168.0.94:8081', 'server.properties', 'ksql_schema监听地址');
INSERT INTO sys_para VALUES ('158', 'ksql_connect', 'http://172.168.0.94:8080', 'server.properties', 'ksql链接地址');
INSERT INTO sys_para VALUES ('159', 'restAuthority', '', 'server.properties', '对于SQL的字段是否使用字段验证');
INSERT INTO sys_para VALUES ('160', 'sys_dateformat', 'yyyy-MM-dd', 'server.properties', '系统日期参数格式化定义');
INSERT INTO sys_para VALUES ('161', 'writemultiplefiles', '1', 'server.properties', '卸数时是否写多个文件(默认1 否)');
INSERT INTO sys_para VALUES ('162', 'file_blocksize', '1024', 'server.properties', '写单个文件大小(单位:M),建议128M的整数倍,默认1G(2G则写成2048)');
--INSERT INTO sys_para VALUES ('155', 'spark.yarn.jars', '/hrds/yuanqi/', 'server.properties', 'hdfs路径，spark在yarn-client模式下运行所需jar包所在的目录(..../spark_lib)的上级目录');
INSERT INTO sys_para VALUES ('167', 'load.executor.count', '2', 'server.properties', '集市并发线程数量，当isconcurrent配置为0时，此配置生效，区间在1~4');
INSERT INTO sys_para VALUES ('166', 'mpp.batch.size', '5000', 'server.properties', 'spark通过jdbc写入到数据库，单批次提交的数量');
INSERT INTO sys_para VALUES ('163', 'isconcurrent', '0', 'server.properties', '集市是否采用多线程作业，0：是，1：否');
INSERT INTO sys_para VALUES ('172', 'hdfsDataPath', '/hrds/TMP/', 'server.properties', '存放接口临时数据文件的地方');
INSERT INTO sys_para VALUES ('169', 'sysnumber', 2000000, 'server.properties', '数据表记录阈值,超过时使用spark程序生成文件');
INSERT INTO sys_para VALUES ('174', 'skipbadrecord', 1, 'server.properties', '卸数是是否跳过错误值默认否(1)');
INSERT INTO sys_para VALUES ('175', 'is_rpc', '1', 'server.properties', '数据加工是否使用RPC调用算法根据源表中英文名智能推荐模型表字段中英文名和分类，是：0；否：1');
INSERT INTO sys_para VALUES ('176', 'rpc_translate_connect', 'http://172.168.0.93:8064', 'server.properties', '数据加工调用算法进行翻译的rpc服务的连接');
INSERT INTO sys_para VALUES ('177', 'rpc_category_connect', 'http://172.168.0.93:8063', 'server.properties', '数据加工调用算法进行分类的rpc服务的连接');
INSERT INTO sys_para VALUES ('178', 'directwritehdfs', '0', 'server.properties', '是否直接写hdfs(默认1 否)');
INSERT INTO sys_para VALUES ('179', 'StreamingProHdfsPath', '/hrds/json/', 'server.properties','流计算json配置文件存放的hdfs的位置');
INSERT INTO sys_para VALUES ('180', 'streamingProJar', 'file:///opt/yj/fullgoal/streamingpro-spark-2.0-1.1.0.jar','server.properties', '流计算执行的jar包部署的位置');
INSERT INTO sys_para VALUES ('181', 'StreamProExecut', 'spark2-submit','server.properties', '流计算执行框架提交的脚本');
INSERT INTO sys_para VALUES ('182', 'hyren_pwd', 'q1w2e3',  'server.properties', '系统默认海云用户的密码');
INSERT INTO sys_para VALUES ('183', 'agentDeployPath', '/home/hyshf/HrsDSP/hrserver', 'server.properties', '海云用户默认的安装路径');
INSERT INTO sys_para VALUES ('184', 'ETLpath', '/home/hyshf/HrsDSP/agentCollect/ETL.tar.gz', 'server.properties', 'ETL下载地址');
INSERT INTO sys_para VALUES ('185', 'mrsize', '10240', 'server.properties', '当文件大小超过此值时使用mr程序处理原始文件(单位:M)');
INSERT INTO sys_para VALUES ('186', 'ocr_rpc_cpu', 'http://10.71.4.57:33333', 'server.properties', 'OCR图片文字识别的RPC服务器地址');
INSERT INTO sys_para VALUES ('187', 'ocr_rpc_use', '0', 'server.properties', '决定OCR图片识别使用的是OCR RPC还是Apache OCR (1-使用OCR PRC,0-使用Apache OCR.默认使用0 Apache OCR)');
INSERT INTO sys_para VALUES ('188', 'pic_rpc_cpu', 'http://10.71.4.55:33332', 'server.properties', '以图搜图模糊搜索RPC服务器地址');
INSERT INTO sys_para VALUES ('189', 'redis_ip', '10.71.4.61', 'server.properties', 'Redis服务IP');
INSERT INTO sys_para VALUES ('190', 'redis_port', '56379', 'server.properties', 'Redis端口');
INSERT INTO sys_para VALUES ('191', 'predict_address', 'http://139.9.126.19:38081/predict', 'server.properties','数据对标-标准预测地址');
